ConsoleWrite("A " & @ProgramFilesDir & @CRLF)
ConsoleWrite("B " & @CommonFilesDir & @CRLF)
ConsoleWrite("C " & @MyDocumentsDir & @CRLF)
ConsoleWrite("D " & @AppDataCommonDir & @CRLF)
ConsoleWrite("E " & @DesktopCommonDir & @CRLF)
ConsoleWrite("F " & @DocumentsCommonDir & @CRLF)
ConsoleWrite("G " & @FavoritesCommonDir & @CRLF)
ConsoleWrite("H " & @ProgramsCommonDir & @CRLF)
ConsoleWrite("I " & @StartMenuCommonDir & @CRLF)
ConsoleWrite("J " & @StartupCommonDir & @CRLF)
ConsoleWrite("K " & @AppDataDir & @CRLF)
ConsoleWrite("L " & @DesktopDir & @CRLF)
ConsoleWrite("M " & @FavoritesDir & @CRLF)
ConsoleWrite("N " & @ProgramsDir & @CRLF)
ConsoleWrite("O " & @StartMenuDir & @CRLF)
ConsoleWrite("P " & @StartupDir & @CRLF)
ConsoleWrite(@CR & @LF)